build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    tests-and-coverage:
      environment:
        php:
          version: 8.0.0
      tests:
        override:
          - phpcs-run ./src
          - command: "vendor/bin/phpunit test/phpunit --coverage-clover coverage --whitelist src -d XDEBUG_MODE=coverage"
            coverage:
              file: "coverage"
              format: "php-clover"

checks:
  php:
    code_rating: true
    duplication: true

filter:
  excluded_paths:
    - test/*
    - vendor/*